CC = gcc
CFLAGS = -Wall

3p17: $@.c
	$(CC) $(CFLAGS) $< -lm -o $@

3p19: $@.c
	$(CC) $(CFLAGS) $< -o $@

3p25: $@.c
	$(CC) $(CFLAGS) $< -o $@

3p32: $@.c
	$(CC) $(CFLAGS) $< -o $@

3p37: $@.c
	$(CC) $(CFLAGS) $< -lm -o $@

sort: $@.c
	$(CC) $(CFLAGS) $< -o $@
